name: Build Container Images

# This workflow will run on:
# 1. Pushes to the 'main' branch (for 'latest' tag).
# 2. Pushes of Git tags that match the pattern 'v*.*.*' (e.g., v1.0.0, v2.1.5).
on:
  push:
    tags:
      - '*.*.*'

# Define environment variables that will be used across jobs.
env:
  # REGISTRY: The container registry to push images to.
  #   - For GitHub Container Registry (GHCR), use 'ghcr.io'.
  #   - For Docker Hub, use 'docker.io'.
  REGISTRY: ghcr.io

  # ORG_NAME: The organization or user name under which the images will be stored.
  #   - For GHCR, this is typically your GitHub username or organization name.
  #   - For Docker Hub, this is your Docker Hub username.
  ORG_NAME: ${{ github.repository_owner }}

jobs:
  # This job builds and pushes the container image.
  build_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read    # Required to checkout the repository.
      packages: write   # Required to push images to GitHub Container Registry.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        # Buildx is a Docker CLI plugin for extended build capabilities, including multi-platform builds.
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }} # Uses the GitHub actor (username) for login.
          # For GHCR, use GITHUB_TOKEN which is automatically provided by GitHub Actions.
          # For Docker Hub, you would typically use a personal access token stored as a repository secret (e.g., ${{ secrets.DOCKER_HUB_TOKEN }}).
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Container metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.ORG_NAME }}/${{ github.event.repository.name }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push main image
        uses: docker/build-push-action@v6
        with:
          context: . # The build context is the root of your repository.
          push: true # Set to 'true' to push the image to the registry.
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64 # Specify target platforms for multi-architecture builds.
