name: Build Container Images

on:
  push:
    tags:
      - '*.*.*'

env:
  REGISTRY: ghcr.io
  ORG_NAME: ${{ github.repository_owner }}
  CARGO_INCREMENTAL: 0

jobs:
  meta:
    name: Generate Container Metadata
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      version: ${{ steps.meta.outputs.version }}
      metadata_json: ${{ steps.meta.outputs.json }}
      image_name: ${{ steps.meta.outputs.image }}
      
    steps:
      - name: Checkout repository (required for semver tag discovery)
        uses: actions/checkout@v4
      
      - name: Container metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.ORG_NAME }}/${{ github.event.repository.name }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}

  build:
    runs-on: ubuntu-latest
    needs: 
      - meta
    permissions:
      contents: read
      packages: write
    env:
      PLATFORMS: linux/amd64,linux/arm64
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ env.PLATFORMS }}
          labels: ${{ needs.meta.outputs.labels }}
          tags: ${{ needs.meta.outputs.tags }}
          push: true
